apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sql-server-deploy
  title: SQL Server Deployment
  description: Deploy SQL Server on-premises or cloud via AWX
spec:
  owner: infra-team
  type: service
  parameters:
    - title: General Information (Page 1)
      required:
        - ammCode
        - environment
        - serverName1
        - features
        - rtoNumber
      properties:
        # AMM Code: Mandatory, Dropdown [cite: 12]
        ammCode:
          type: string
          title: AMM Code
          enum: ['AMM01', 'AMM02', 'AMM03'] # Populate with real data or use custom fetcher
        
        # Environment: Mandatory, Dropdown (DEV, IT, QA, PROD) [cite: 13]
        environment:
          type: string
          title: Environment
          enum: ['DEV', 'IT', 'QA', 'PROD']
        
        # Server Name 1: Filtered dropdown (Requires Custom Extension) 
        # We use a custom UI field here to handle the "AMM + Env" filtering logic
        serverName1:
          type: string
          title: Server Name 1
          ui:field: SimpleServerSelector 
        
        # Server Name 2: Optional, triggers AlwaysOn [cite: 16]
        serverName2:
          type: string
          title: Server Name 2
          ui:field: SimpleServerSelector
        
        # AlwaysOn Instance: Conditional boolean [cite: 17]
        # Logic: Only appears if serverName2 is populated (handled via dependencies below)
        alwaysOnInstance:
          type: boolean
          title: Enable AlwaysOn Instance
          default: false
        
        # Features: Multi-select, Default SQLENGINE [cite: 19]
        features:
          type: array
          title: Features
          uniqueItems: true
          items:
            type: string
            [cite_start]enum: ['SQLENGINE', 'FULLTEXT', 'REPLICATION', 'AS', 'IS', 'RS', 'CONN', 'BC', 'SDK'] [cite: 22]
          default: ['SQLENGINE']
          ui:options:
            orderable: false
            
        # Instance Name: Readonly, Autogenerated [cite: 24]
        instanceName:
          type: string
          title: Generated Instance Name
          readOnly: true
          ui:field: AutoGenInstanceName # Custom field to handle logic
          
        # RTO Number: 6-digit numeric [cite: 34]
        rtoNumber:
          type: string # String allows regex validation easily
          title: RTO Number
          pattern: '^\d{6}$'
    - title: SQL Configuration (Page 2)
      required:
        - sqlVersion
        - sqlEdition
        - collation
      properties:
        # SQL Version: Default 2022 [cite: 36]
        sqlVersion:
          type: string
          title: SQL Version
          enum: ['2016', '2019', '2022', '2025']
          default: '2022'
        
        # SQL Edition: Rules applied via Custom Extension 
        sqlEdition:
          type: string
          title: SQL Edition
          ui:field: DynamicSqlEditionSelector # Handles Dev/Prod constraints
        
        # Collation: Default provided [cite: 38]
        collation:
          type: string
          title: Collation
          default: 'SQL_Latin1_General_CP1_CI_AS'
          
        # Database Names: List of strings [cite: 39]
        databaseNames:
          type: array
          title: Database Names
          items:
            type: string
    - title: Network & Witness (Page 3)
        properties:
          # Witness section is conditional 
          witnessName:
            type: string
            title: Witness Name
          witnessKey:
            type: string
            title: Witness Key
            ui:widget: password
            
          # AlwaysOn Network Config 
          alwaysOnListenerIp:
            type: string
            title: AlwaysOn Listener IP
            [cite_start]pattern: '^((25[0-5]|2[0-4]|1d|[1-9]|)\d)\.?\b){4}$' # Regex from PDF 
          alwaysOnNetmask:
            type: string
            title: AlwaysOn Netmask
            
          # Failover Config [cite: 62]
          failoverSqlRoleIp:
            type: string
            title: Failover SQL Role IP
            pattern: '^((25[0-5]|2[0-4]|1d|[1-9]|)\d)\.?\b){4}$'
          roleNetmask:
            type: string
            title: Role Netmask
            
        # Logic to show/hide fields based on previous inputs
        dependencies:
          alwaysOnInstance:
            oneOf:
              - properties:
                  alwaysOnInstance:
                    const: true
                required:
                  - alwaysOnListenerIp
                  - alwaysOnNetmask
              - properties:
                  alwaysOnInstance:
                    const: false
                required:
                  - failoverSqlRoleIp
                  - roleNetmask