apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: sql-server-deploy
  title: SQL Server Deployment
  description: Deploy Microsoft SQL Server on-premises and in cloud (Azure, GCP)
  tags:
    - sql
    - windows
    - awx
spec:
  owner: infra-group
  type: service

  # -----------------------------------------------------------------------------
  # INPUT PARAMETERS (The Form)
  # -----------------------------------------------------------------------------
  parameters:
    # PAGE 1: General Information
    - title: General Information
      required:
        - ammCode
        - environment
        - serverName1
        - features
        - rtoNumber
      properties:
        # AMM Code: Mandatory, Dropdown
        ammCode:
          title: AMM Code
          type: string
          enum: ['AMM01', 'AMM02', 'AMM03']
          description: Used for filtering server names

        # Environment: Mandatory, Dropdown (DEV, IT, QA, PROD)
        environment:
          title: Environment
          type: string
          enum: ['DEV', 'IT', 'QA', 'PROD']
          description: Used for filtering and name generation

        # Server Name 1: Filtered by AMM + Env
        # NOTE: Needs a Custom Field Extension to handle the filtering logic
        serverName1:
          title: Server Name 1
          type: string
          description: Select the primary server (Hostname only)
          ui:field: ServerNamePicker
          ui:options:
            filterByAmm: ammCode
            filterByEnv: environment

        # Server Name 2: Optional
        serverName2:
          title: Server Name 2
          type: string
          description: Select secondary server if applicable
          ui:field: ServerNamePicker
          ui:options:
            filterByAmm: ammCode
            filterByEnv: environment

        # AlwaysOn Instance: Conditional (only if Server 2 selected)
        alwaysOnInstance:
          title: Enable AlwaysOn Instance
          type: boolean
          default: false
          description: Available only when Server Name 2 is selected

        # Features: Multi-select, Default SQLENGINE
        features:
          title: SQL Features
          type: array
          uniqueItems: true
          items:
            type: string
            enum: ['SQLENGINE', 'FULLTEXT', 'REPLICATION', 'AS', 'IS', 'RS', 'CONN', 'BC', 'SDK']
          default: ['SQLENGINE']
          description: SQLENGINE is mandatory and cannot be deselected
          ui:widget: checkboxes
          ui:options:
            orderable: false

        # Instance Name: Readonly, Autogenerated
        # NOTE: Needs a Custom Field Extension to handle the "SQL+AMM..." pattern
        instanceName:
          title: Instance Name (Auto-generated)
          type: string
          readOnly: true
          description: Format SQL[AMM][Env][Type][Number]
          ui:field: InstanceNameGenerator
          ui:options:
            ammCode: ammCode
            environment: environment

        # RTO Number: 6-digit numeric
        rtoNumber:
          title: RTO Number
          type: string
          pattern: '^\d{6}$'
          description: Must be a 6-digit numeric value

    # PAGE 2: SQL Configuration
    - title: SQL Configuration
      required:
        - sqlVersion
        - sqlEdition
        - collation
      properties:
        # SQL Version: Default 2022
        sqlVersion:
          title: SQL Version
          type: string
          enum: ['2016', '2019', '2022', '2025']
          default: '2022'

        # SQL Edition: Rules applied via Logic (Dev vs Prod)
        # NOTE: Needs Custom Field Extension for the Dev/Prod constraints
        sqlEdition:
          title: SQL Edition
          type: string
          enum: ['Developer', 'Standard', 'Enterprise', 'Developer Standard', 'Developer Enterprise']
          description: Available options depend on SQL Version and Environment
          ui:field: SqlEditionPicker
          ui:options:
            sqlVersion: sqlVersion
            environment: environment

        # Collation: Default provided
        collation:
          title: Collation
          type: string
          default: 'SQL_Latin1_General_CP1_CI_AS'
          description: SQL Server collation setting

        # Database Names: Optional list
        databaseNames:
          title: Database Names
          type: array
          items:
            type: string
          description: Optional comma-separated list of databases to create (case-sensitive)

    # PAGE 3: Network & Witness (Conditional)
    - title: Network & Witness Configuration
      properties:
        # Witness Configuration (Only if 2 servers + Azure)
        witnessName:
          title: Witness Name
          type: string
          description: Required only for Azure deployments with 2 servers

        witnessKey:
          title: Witness Key
          type: string
          ui:widget: password
          description: Required only for Azure deployments with 2 servers

        # AlwaysOn Network Config
        alwaysOnListenerIp:
          title: AlwaysOn Listener IP
          type: string
          pattern: '^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$'
          description: Required when AlwaysOn is enabled

        alwaysOnNetmask:
          title: AlwaysOn Netmask
          type: string
          description: Required when AlwaysOn is enabled

        # Failover SQL Role IP
        failoverSqlRoleIp:
          title: Failover SQL Role IP
          type: string
          pattern: '^((25[0-5]|(2[0-4]|1\d|[1-9]|)\d)\.?\b){4}$'
          description: Required when AlwaysOn is disabled

        roleNetmask:
          title: Role Netmask
          type: string
          description: Required when AlwaysOn is disabled
      
      # Logic to toggle fields based on AlwaysOn selection
      dependencies:
        alwaysOnInstance:
          oneOf:
            - properties:
                alwaysOnInstance:
                  const: true
              required:
                - alwaysOnListenerIp
                - alwaysOnNetmask
            - properties:
                alwaysOnInstance:
                  const: false
              required:
                - failoverSqlRoleIp
                - roleNetmask

  # -----------------------------------------------------------------------------
  # STEPS (The Action)
  # -----------------------------------------------------------------------------
  steps:
    - id: log-message
      name: Log Inputs
      action: debug:log
      input:
        message: "Deploying SQL to ${{ parameters.serverName1 }}"

    # Trigger AWX Job
    # You will need to install the backstage-plugin-scaffolder-backend-module-awx 
    # or write a custom action to make this work.
    - id: trigger-awx
      name: Trigger AWX Job Template
      action: awx:job:launch 
      input:
        jobTemplateName: "SQL_Deploy_Template"
        extra_vars:
          amm_code: ${{ parameters.ammCode }}
          environment: ${{ parameters.environment }}
          server_name_1: ${{ parameters.serverName1 }}
          server_name_2: ${{ parameters.serverName2 }}
          always_on: ${{ parameters.alwaysOnInstance }}
          features: ${{ parameters.features }}
          instance_name: ${{ parameters.instanceName }}
          rto_number: ${{ parameters.rtoNumber }}
          sql_version: ${{ parameters.sqlVersion }}
          sql_edition: ${{ parameters.sqlEdition }}
          collation: ${{ parameters.collation }}
          database_names: ${{ parameters.databaseNames }}
          witness_name: ${{ parameters.witnessName }}
          witness_key: ${{ parameters.witnessKey }}
          listener_ip: ${{ parameters.alwaysOnListenerIp }}
          listener_netmask: ${{ parameters.alwaysOnNetmask }}
          failover_ip: ${{ parameters.failoverSqlRoleIp }}
          failover_netmask: ${{ parameters.roleNetmask }}

  # -----------------------------------------------------------------------------
  # OUTPUT
  # -----------------------------------------------------------------------------
  output:
    links:
      - title: Open AWX
        url: https://awx.yourcompany.com
      - title: View Deployment Details
        url: https://backstage.yourcompany.com/catalog/default/component/${{ parameters.instanceName | lower }}